name: Go

on:
  push:
    # Sequence of patterns matched against refs/heads
#     branches:    
#       - master         # Push events on master branch
#       - 'mona/octocat' # Push events to branches matching refs/heads/mona/octocat
#       - 'releases/**'  # Push events to branches matching refs/heads/releases/10
    # Sequence of patterns matched against refs/tags
    tags:        
      - v*.*.*           # Push events to v1.0.0, v1.1.0, and v1.9.0 tags
  pull_request:
    branches: [ master ]


jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
    
    - name: Test release version
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
        
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
  
    - name: Docker build push with action
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: woodsmur/github-action-playground

    - name: Docker build push
      run: docker build -t woodsmur/github-action-playground:$RELEASE_VERSION .

    - name: Docker list images
      run: docker images

    - name: Docker Login
      # run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME



    - name: Docker push
      run: docker push woodsmur/github-action-playground:$RELEASE_VERSION
